### ISSUE TITLE
可否编译成服务端/客户端不加任何参数运行的时候，直接默认参数执行

### ISSUE THREAD

**Issue by poppy7921** [seventeenman/Forest#1]
默认参数建议为加载同目录下的加密后字符串文件
比如服务端不加参数，默认加载同目录的forests.dat
       客户端不加参数，默认加载同目录的forestc.dat

dat文件里面的内容就是加密后的字符串

当然，能自由修改默认文件名就更好了。

**Comment by poppy7921** [comment]
没默认加密文件的时候，提示找不到文件，让用户执行--help查看用法

**Comment by seventeenman** [comment]
> 默认参数建议为加载同目录下的加密后字符串文件 比如服务端不加参数，默认加载同目录的forests.dat 客户端不加参数，默认加载同目录的forestc.dat
> 
> dat文件里面的内容就是加密后的字符串
> 
> 当然，能自由修改默认文件名就更好了。

师傅你好，首先感谢你的建议。
相信你有观察到不加参数的时候输出no log等字样，本意是能将此工具伪造为日志文件而隐藏于目标服务器上。
有考虑到个别师傅内部c2不支持这么长的参数，所以有添加了-f参数指定加载加密后字符串文件。
如果有什么建议或者bug欢迎师傅继续发issue。

**Comment by poppy7921** [comment]
可否无参数运行后，照样输出no log等字样后退出，实际上加载同目录的默认加密字符串文件在后台运行呢？

**Comment by seventeenman** [comment]
> 可否无参数运行后，照样输出no log等字样后退出，实际上加载同目录的默认加密字符串文件在后台运行呢？

因为我公司组里已经有编译前就写死在工具里的代理工具，所以暂时不考虑这个功能。
