### ISSUE TITLE
解压密码是什么

### ISSUE THREAD

**Issue by 281066586** [seventeenman/Forest#2]

**Comment by seventeenman** [comment]
[https://github.com/seventeenman/Forest/releases/tag/Forest](https://github.com/seventeenman/Forest/releases/tag/Forest)
release页面里面有写解压密码: forest。

**Comment by seventeenman** [comment]
[https://github.com/seventeenman/Forest/releases/tag/Forest](https://github.com/seventeenman/Forest/releases/tag/Forest)
release页面里面有写解压密码: forest
