### ISSUE TITLE
服务器默认端口如何修改 好像默认就是7000

### ISSUE THREAD

**Issue by FuckTheLife** [seventeenman/Forest#6]
修改frpc.ini的server_port参数好像没生效 服务器默认就是在监听7000端口

**Comment by seventeenman** [comment]
<img width="931" alt="image" src="https://user-images.githubusercontent.com/84114371/193819717-216fb09b-7fe7-4895-9d56-608f47950512.png">

**Comment by FuckTheLife** [comment]
已经修改过iniPath 修改了端口 但服务器端默认还是监听的7000端口

**Comment by seventeenman** [comment]
你好，可以发一下ini看看

**Comment by FuckTheLife** [comment]
[common]
server_addr = XX.XX.XX.XX
server_port = 11123
token = forest
tls_enable = true
use_compression = true

[d5b4]
type = tcp
remote_port = 9000
plugin = socks5
plugin_user = forest
plugin_passwd = forest

**Comment by seventeenman** [comment]
看了你发的这个配置是frpc.ini客户端那边的，加密后是在客户端那边执行forestc.exe -e {加密后的字符串}
你这个配置对应的服务端frps.ini应该如下
```
[common]
bind_addr = 0.0.0.0
bind_port = 11123
token = forest
```
frps.ini加密后用forests.exe -e {加密后的字符串}
forestc即为frpc，forests即为frps

**Comment by FuckTheLife** [comment]
go run main.go 生成密文
服务端 ./forests_linux_amd64 -e  能正常启动程序 但监听的是默认端口 
forests tcp listen on 0.0.0.0:7000

哦 您的意思是要把服务端和客户端的配置文件分别生成e密文吗?  我以为只要读取一个客户端的配置文件就行了 感觉两个配置文件有点重复了

**Comment by seventeenman** [comment]
是的，因为实际环境中如果多层隧道的话，frps那边也是需要配置文件进行修改

**Comment by seventeenman** [comment]
实际上和原版frp用法差不多，只不过在此之前先把配置文件加密了

**Comment by FuckTheLife** [comment]
好的 按照您的指导 已经解决了 感谢回复
