### ISSUE TITLE
frp无文件落地，如何解决cobaltstrike的1m问题？

### ISSUE THREAD

**Issue by ddostest123** [seventeenman/Forest#8]
师傅您好！😁
我留意到您的项目有提到frp内存加载，并且提到cobaltstrike的cna插件。
请问一下，您是通过reflective dll 的方式实现的吗？reflective限制了只能加载1m大小的文件，您如何解决啊？

**Comment by seventeenman** [comment]
> 师傅您好！😁 我留意到您的项目有提到frp内存加载，并且提到cobaltstrike的cna插件。 请问一下，您是通过reflective dll 的方式实现的吗？reflective限制了只能加载1m大小的文件，您如何解决啊？

我考虑的还是内存加载pe文件这块去扩展，感兴趣可以留个邮箱聊聊

**Comment by ddostest123** [comment]
不好意思呀，没留意到师傅您的回复。我讨了个巧，中间是有用到内存加载pe文件的方式实现了。效果很不错的。

**Comment by ddostest123** [comment]
不好意思呀，没留意到师傅您的回复。我讨了个巧，中间是有用到内存加载pe文件的方式实现了，另外也结合了其他的技巧，中间还有参数传递的问题等，如果师傅您研究到了后，可能也会遇到，很有意思，最后测试效果很不错的。🤓

**Comment by seventeenman** [comment]
> 不好意思呀，没留意到师傅您的回复。我讨了个巧，中间是有用到内存加载pe文件的方式实现了，另外也结合了其他的技巧，中间还有参数传递的问题等，如果师傅您研究到了后，可能也会遇到，很有意思，最后测试效果很不错的。🤓

可以的，c++在解析完pe的IAT表hook getcommandline那几个api的时候可能会有点问题，解决了就行

**Comment by ddostest123** [comment]
😊
